from distutils.core import setup

setup(name='seispy',
      version='1.0',
      description='Seismic data analysis tool',
      author='Malcolm White',
      author_email='white.m88@gmail.com',
      download_url='https://github.com/malcolmw/SeisPy',
      requires=['obspy'],
      packages=['seispy',
                'seispy.antelope',
                'seispy.core',
                'seispy.util'],
      py_modules=['seispy.antelope.brttpkt',
                  'seispy.antelope.coords',
                  'seispy.antelope.datascope',
                  'seispy.antelope.elog',
                  'seispy.antelope.orb',
                  'seispy.antelope.Pkt',
                  'seispy.antelope.stock',
                  'seispy.core.arrival',
                  'seispy.core.channel',
                  'seispy.core.database',
                  'seispy.core.dbparsable',
                  'seispy.core.exceptions',
                  'seispy.core.network',
                  'seispy.core.origin',
                  'seispy.core.iterators',
                  'seispy.core.station',
                  'seispy.core.trace',
                  'seispy.core.virtualnetwork',
                  'seispy.util.mtp',
                  'seispy.util.schema',
                  'seispy.util.time'],
      scripts=['scripts/tests/test_arrival',
               'scripts/tests/test_origin',
               'scripts/tests/test_station',
               'scripts/tests/test_trace',
               'scripts/tests/test_database']
      )
