#!/usr/bin/env python
import sys
import os
sys.path.append('%s/data/python' % os.environ['ANTELOPE'])
from antelope.datascope import dbopen
from seispy.core.arrival import Arrival
db = dbopen('/Users/mcwhite/staging/dbs/anza/2005/anza_2005')
tbl_arrival = db.lookup(table='arrival')
tbl_arrival.record = 0
arr = Arrival(tbl_arrival)
print arr
