#!/usr/bin/env python

from obspy.core.utcdatetime import UTCDateTime

from gazelle.datascope import Database
from seispy.core import Arrival, Trace

db = Database('/home/shake/malcolcw/data/wfs/ramona')
network = db.parse_network('YN')
station = network.stations['RA09']
time= UTCDateTime(year=2015, julday=003, hour=9, minute=49, second=12)
gather = db.get_gather3c(station,
                         station.get_channel_set("HN"),
                         time,
                         time + 20)
gather.filter('bandpass', freqmin=3.0, freqmax=20.0)
#gather.polarize()
detections = [gather.detectS()]
print detections[0].time, detections[0].channel
gather.plot(detections=detections, xticklabel_fmt="%H:%M:%S.%f")
db.close()
