#!/usr/bin/env python
from gazelle.datascope import Database
db = Database("/home/shake/malcolcw/data/synthetics/test/SJFZ_synth")
for origin in db.iterate_events(parse_magnitudes=False):
    for arrival in origin.arrivals:
        print arrival
