#!/usr/bin/env/python
import sys
import os
sys.path.append('{:s}/data/python'.format(os.environ['ANTELOPE']))
from antelope.datascope import dbopen, closing

from seispy.core.trace import Trace

with closing(dbopen('/Users/mcwhite/staging/wfs/dummy/db', 'r')) as db:
    tbl_wfdisc = db.lookup(table='wfdisc')
    tbl_wfdisc.record = 0
    tr = Trace(tbl_wfdisc)

print tr
