#!/opt/antelope/5.5/bin/python

from seispy.core import Station
#from seispy import antelope

from seispy.antelope.datascope import dbopen

def main():
    db = dbopen('/Users/mcwhite/staging/dbs/3drelocate/dbmaster/anza')
    tbl_site = db.lookup(table='site')
    view = tbl_site.join('sitechan')
    view.record = 0
    sta = Station(view)
    print sta
    db.close()

if __name__ == '__main__':
    main()
