#!/usr/bin/env python
import sys
import os

from seispy.core import Trace
from obspy.core import read
import seispy
import gazelle.datascope
from gazelle.datascope import closing,\
                              dbopen

with closing(dbopen('/home/shake/malcolcw/data/wfs/ramona', 'r')) as db:
    tbl_wfdisc = db.lookup(table='wfdisc')
    tbl_wfdisc.record = 0
    tr = Trace(tbl_wfdisc)

print tr
