#!/usr/bin/env python
import sys
import os
sys.path.append('%s/data/python' % os.environ['ANTELOPE'])
from antelope.datascope import dbopen
from seipy.core.origin import Origin
db = dbopen('/Users/mcwhite/staging/dbs/anza/2005/anza_2005')
tbl_origin = db.lookup(table='origin')
tbl_origin.record = 0
origin = Origin(tbl_origin)
print origin
origin = Origin(23.0174, -116.7823, 14.790, 1462614225.544)
print origin
